blank_issues_enabled: true
contact_links:
  - name: 📚 Documentação
    url: https://github.com/SWIFT/wiki
    about: Consulte nossa documentação para dúvidas gerais
  - name: 💬 Discussões
    url: https://github.com/SWIFT/discussions
    about: Participe das discussões da comunidade
